# use https://ergogen.ceoloide.com/ which includes more footprints

units:
  kx: u
  ky: u
  px: u + 2
  py: u + 2

points:
  zones:
    matrix:
      anchor:
        shift: [70,-140]
      columns:
        outer:
          rows:
            mod:
              skip: true
        pinky:
        ring:
          key:
            stagger: 12
        middle:
          key:
            stagger: 8
        index:
          key:
            stagger: -5
        inner:
          key:
            stagger: -3
      rows:
        bottom:
        home:
        top:
    thumbs:
      key:
        padding: 1kx
        spread: 1kx 
      anchor:
        ref: matrix_pinky_bottom
        shift: [36, -8]
      columns:
        alt: 
        super:
        layer:
          key:
            splay: -20
            rotate:
            spread: 1.2kx
            shift: [0,-4]
        space:
          key:
            splay: -95
            shift: [5,1.5]
            width: 1.25kx
      rows:
        cluster:
  #mirror: &mirror
  #  ref: matrix_inner_top
  #  distance: 4kx
outlines:
  board:
    - what: polygon
      operation: stack
      points:
      - ref: matrix_outer_top
        shift: [-0.5px,0.5py]
      - ref: matrix_pinky_top
        shift: [0.4px,0.5py]
      - ref: matrix_ring_top
        shift: [-.5px,0.5py]
      - ref: matrix_middle_top
        shift: [-.5px,.13py]
      - ref: matrix_middle_top
        shift: [-0.5px,0.5py]
      - ref: matrix_index_top
        shift: [-0.4px,0.75py]
      - ref: matrix_index_top
        shift: [-.4px,0.5py]
      - ref: matrix_inner_top
        shift: [-.4px, .65py]
      - ref: matrix_inner_top
        shift: [-.4px, .5py]
      - ref: matrix_inner_top
        shift: [1.8px, .5py]
      - ref: matrix_inner_home
        shift: [1.8px,-.4py]
      - ref: matrix_inner_home
        shift: [.8px,-1.8py]
      - ref: matrix_inner_bottom
        shift: [1.55px, -1.25py]
      - ref: thumbs_layer_cluster
        shift: [1.4px, -.6py]
      - ref: thumbs_super_cluster
        shift: [1.25px,-.8py]
      - ref: thumbs_super_cluster
        shift: [.45px,-.5py]
      - ref: matrix_ring_bottom
        shift: [0.32px,-1.45py]
      - ref: matrix_ring_bottom
        shift: [.3px,-.5py]
      - ref: matrix_ring_bottom
        shift: [-.4px,-.5py]
      - ref: matrix_pinky_bottom
        shift: [0.5px,-0.5py]
      - ref: matrix_outer_bottom
        shift: [-0.5px,-0.5py]
      fillet: 2

  raw:
    - what: rectangle
      where: true
      size: [1.2px, 1.2py]
      fillet: 2
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [1kx, 1ky]
  combo:
  - name: board
  - operation: subtract
    name: keys
pcbs:
  SebCorne:
    outlines:
      main:
        outline: board
    footprints:
      # Hotswap Choc keys.
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          side: "b"
        adjust:
          shift: [0, -5]
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          side: "f"
        where:
          ref.aggregate.parts: [matrix_inner_top]
          shift: [21, -8]
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: "f"
