units:
  kx: U
  ky: U
  px: U + 2
  py: U + 2

points:
  zones:
    matrix:
      anchor:
        shift: [75,-150]
      columns:
        outer:
          key.column_net: P1
        pinky:
          key.column_net: P0
        ring:
          key:
            stagger: 12
          key.column_net: P2
        middle:
          key:
            stagger: 8
          key.column_net: P3
        index:
          key:
            stagger: -5
          key.column_net: P4
        inner:
          key:
            stagger: -3
          key.column_net: P5
      rows:
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
    thumbs:
      key:
        padding: 1kx
        spread: 1kx 
      anchor:
        ref: matrix_pinky_bottom
        shift: [36, -8]
      columns:
        alt:
          key.column_net: P2
        super:
          key.column_net: P3
        layer:
          key:
            splay: -20
            rotate:
            spread: 1.2kx
            shift: [0,-4]
          key.column_net: P4
        space:
          key:
            splay: -95
            shift: [5,1.5]
            width: 1.25kx
          key.column_net: P5
      rows:
        cluster:
          row_net: P9
  mirror: &mirror
    ref: matrix_inner_top
    distance: 4kx
outlines:
  board_left:
    - what: polygon
      operation: stack
      points:
      - ref: matrix_outer_top
        shift: [-0.5px,0.5py]
      - ref: matrix_pinky_top
        shift: [0.4px,0.5py]
      - ref: matrix_ring_top
        shift: [-.5px,0.5py]
      - ref: matrix_middle_top
        shift: [-.5px,.13py]
      - ref: matrix_middle_top
        shift: [-0.5px,0.5py]
      - ref: matrix_index_top
        shift: [-0.4px,0.75py]
      - ref: matrix_index_top
        shift: [-.4px,0.5py]
      - ref: matrix_inner_top
        shift: [-.4px, .65py]
      - ref: matrix_inner_top
        shift: [-.4px, .5py]
      - ref: matrix_inner_top
        shift: [1.5px, .5py]
      - ref: matrix_inner_home
        shift: [1.5px,-.4py]
      - ref: matrix_inner_home
        shift: [.8px,-1.8py]
      - ref: matrix_inner_bottom
        shift: [1.55px, -1.25py]
      - ref: thumbs_layer_cluster
        shift: [1.4px, -.6py]
      - ref: thumbs_super_cluster
        shift: [1.25px,-.8py]
      - ref: thumbs_super_cluster
        shift: [.45px,-.5py]
      - ref: matrix_ring_bottom
        shift: [0.32px,-1.45py]
      - ref: matrix_ring_bottom
        shift: [.3px,-.5py]
      - ref: matrix_ring_bottom
        shift: [-.4px,-.5py]
      - ref: matrix_pinky_bottom
        shift: [0.5px,-0.5py]
      - ref: matrix_outer_bottom
        shift: [-0.5px,-0.5py]
      fillet: 2
  board_right:
    - what: polygon
      operation: stack
      points:
      - ref: mirror_matrix_outer_top
        shift: [-0.5px,0.5py]
      - ref: mirror_matrix_pinky_top
        shift: [0.4px,0.5py]
      - ref: mirror_matrix_ring_top
        shift: [-.5px,0.5py]
      - ref: mirror_matrix_middle_top
        shift: [-.5px,.13py]
      - ref: mirror_matrix_middle_top
        shift: [-0.5px,0.5py]
      - ref: mirror_matrix_index_top
        shift: [-0.4px,0.75py]
      - ref: mirror_matrix_index_top
        shift: [-.4px,0.5py]
      - ref: mirror_matrix_inner_top
        shift: [-.4px, .65py]
      - ref: mirror_matrix_inner_top
        shift: [-.4px, .5py]
      - ref: mirror_matrix_inner_top
        shift: [1.5px, .5py]
      - ref: mirror_matrix_inner_home
        shift: [1.5px,-.4py]
      - ref: mirror_matrix_inner_home
        shift: [.8px,-1.8py]
      - ref: mirror_matrix_inner_bottom
        shift: [1.55px, -1.25py]
      - ref: mirror_thumbs_layer_cluster
        shift: [1.4px, -.6py]
      - ref: mirror_thumbs_super_cluster
        shift: [1.25px,-.8py]
      - ref: mirror_thumbs_super_cluster
        shift: [.45px,-.5py]
      - ref: mirror_matrix_ring_bottom
        shift: [0.32px,-1.45py]
      - ref: mirror_matrix_ring_bottom
        shift: [.3px,-.5py]
      - ref: mirror_matrix_ring_bottom
        shift: [-.4px,-.5py]
      - ref: mirror_matrix_pinky_bottom
        shift: [0.5px,-0.5py]
      - ref: mirror_matrix_outer_bottom
        shift: [-0.5px,-0.5py]
      fillet: 2
  raw:
    - what: rectangle
      where: true
      size: [1.2px, 1.2py]
      fillet: 2
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [1kx, 1ky]
  combo:
  - name: board_left
  - name: board_right
  - operation: subtract
    name: keys
  pcb_outline:
  - name: board_left
  - name: board_right

pcbs:
  CapriCorne:
    outlines:
      main:
        outline: pcb_outline
    footprints:
      # Hotswap Choc keys.
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]

      nice_nano_left:
        what: ceoloide/mcu_supermini_nrf52840.js
        params:
          side: "f"
          reverse_mount: true
        where:
          ref.aggregate.parts: [matrix_inner_top]
          shift: [21, -8]

      nice_nano_right:
        what: ceoloide/mcu_nice_nano
        params:
          side: "f"
          reverse_mount: true
        where:
          ref.aggregate.parts: [mirror_matrix_inner_top]
          shift: [-21, -8]

      battery_connector_left:
        what: ceoloide/battery_connector_jst_ph_2
        params:
        #  BAT_P: 'RAW'
        where:
          ref.aggregate.parts: [matrix_inner_home]
          shift: [16,-19]
          rotate: 153

      power_switch_left:
        what: infused-kim/switch_power
        where:
          ref.aggregate.parts: [matrix_inner_bottom]
          shift: [16,-13]
          rotate: -27

      reset_switch_left:
        what: ceoloide/reset_switch_tht_top
        where:
          ref.aggregate.parts: [matrix_inner_bottom]
          shift: [21, -4.5]
          rotate: 63

      battery_connector_right:
        what: ceoloide/battery_connector_jst_ph_2
        params:
        #  BAT_P: 'RAW'
        where:
          ref.aggregate.parts: [mirror_matrix_inner_home]
          shift: [-16,-19]
          rotate: -153

      power_switch_right:
        what: infused-kim/switch_power
        where:
          ref.aggregate.parts: [mirror_matrix_inner_bottom]
          shift: [-16,-13]
          rotate: -153

      reset_switch_right:
        what: ceoloide/reset_switch_tht_top
        where:
          ref.aggregate.parts: [mirror_matrix_inner_bottom]
          shift: [-21, -4.5]
          rotate: -63

      battery_wires_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '4'
          hole_drill: '4'
        where:
          ref.aggregate.parts: [matrix_inner_home]
          shift: [21,-9]

      battery_wires_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '4'
          hole_drill: '4'
        where:
          ref.aggregate.parts: [mirror_matrix_inner_home]
          shift: [-21,-9]

      mounting_upper_outer_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [matrix_outer_top]
          shift: [9.5, -9.5]

      mounting_bottom_outer_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [matrix_outer_home]
          shift: [9.5, -9.5]

      mounting_bottom_ring_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [matrix_pinky_home]
          shift: [9.5, -9.5]
      
      mounting_top_ring_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [matrix_pinky_top]
          shift: [9.5, -9.5]
      
      mounting_top_index_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [matrix_index_top]
          shift: [9.5, -9.5]
      
      mounting_bottom_middle_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [matrix_middle_bottom]
          shift: [0, -14]

      mounting_top_middle_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [matrix_middle_top]
          shift: [9.5, -9.5]
      
      mounting_bottom_space_left:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [thumbs_layer_cluster]
          shift: [10.7, 8]

      mounting_upper_outer_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_matrix_outer_top]
          shift: [-9.5, -9.5]

      mounting_bottom_outer_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_matrix_outer_home]
          shift: [-9.5, -9.5]

      mounting_bottom_ring_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_matrix_pinky_home]
          shift: [-9.5, -9.5]
      
      mounting_top_ring_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_matrix_pinky_top]
          shift: [-9.5, -9.5]
      
      mounting_top_index_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_matrix_index_top]
          shift: [-9.5, -9.5]
      
      mounting_bottom_middle_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_matrix_middle_bottom]
          shift: [0, -14]

      mounting_top_middle_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_matrix_middle_top]
          shift: [-9.5, -9.5]
      
      mounting_bottom_space_right:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: '3'
          hole_drill: '3'
        where:
          ref.aggregate.parts: [mirror_thumbs_layer_cluster]
          shift: [-10.7, 8]
